### ISSUE TITLE
xarray-leaflet not working properly on Windows

### ISSUE THREAD

**Issue by giswqs** [xarray-contrib/xarray_leaflet#30]
It seems xarray-leaflet is not working properly on Windows. The map tiles could not load. When checking the map tiles under the Temp folders, most tiles are empty. A relevant [issue](https://github.com/giswqs/geemap/issues/195) was reported by another geemap user. 

OS: Windows 10
Python: v3.8
xarray-leaflet: v0.1.13
Notebook: [xarray_leaflet/examples/introduction.ipynb](https://github.com/davidbrochart/xarray_leaflet/blob/master/examples/introduction.ipynb)

![](https://i.imgur.com/7vzfh3D.png)

**Comment by davidbrochart** [comment]
Thanks for reporting @giswqs, I guess the time has come to have tests in xarray-leaflet! I will try to work on this soon.

**Comment by Xabitsuki** [comment]
Hi !
Unfortunately the examples do not work on mac either ... I added layer controls to see if the layer is there and removed the dark basemap, but nothing worked. 

I also tried displaying a band in an other projet by calling xarray.dataarray.plot(m=m) with no success: it's as if the generated layer were transparent or behind the basemap. 

<img width="1241" alt="Screenshot 2021-10-01 at 17 00 28" src="https://user-images.githubusercontent.com/43441377/135643223-64c36d07-9b5d-4730-9cf6-da543755cec8.png">

**Comment by davidbrochart** [comment]
xarray-leaflet got its first test in #49 !

**Comment by haseeb33** [comment]
@giswqs I have been using your library `geemap`. Everything is working fine but this part is not working even on linux for me. It doesn't load the tiff files.
Let's wait for the positive news for both of us(developer like me and contributor like you so your library can work completing because xarray-leaflet is in dependencies of geemap)
My environment:
Python= v3.8
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
xarray-leaflet: v0.10.1 also tried (0.10.2) and older versions (0.1.1) (0.3.1) 

older versions show some errors so didn't proceed with those.

**Comment by vdevauxchupin** [comment]
Hi, I just wanted to see if others still had issues with the layers not loading ? That's the case for me on Windows.

**Comment by lalligagger** [comment]
Still having issues for me on Mac OS 13.4
