### ISSUE TITLE
Installing xarray-leaflet causes jupyter server to be really slow to start

### ISSUE THREAD

**Issue by yuvipanda** [xarray-contrib/xarray_leaflet#79]
On a fresh install (no .pyc files), just importing xarray_leaflet takes about 9s:

```
(notebook) jovyan@jupyter-yuvipanda:~$ time python -c 'import xarray_leaflet'


real    0m9.275s
user    0m8.100s
sys     0m1.134s
```

As this is imported *each time* jupyter server is started, the user can not see their notebook until this initialization is complete. When coupled with other slow loading extensions (such as panel https://github.com/holoviz/panel/issues/4271), this can cause server starts to time out in JupyterHubs. There is no way to disable this (jupyter server will still *import* your package even if it is disabled), so the only way to get a faster startup is to uninstall xarray-leaflet completely.

I think a majority of the import time comes from `rioxarray`

```
(notebook) jovyan@jupyter-yuvipanda:~$ time python -c 'import rioxarray'

real    0m7.707s
user    0m5.787s
sys     0m0.912s
```

**Comment by yuvipanda** [comment]
I opened https://github.com/jupyter-server/jupyter_server/pull/1171 to make this information available more easily.

**Comment by davidbrochart** [comment]
Thanks for reporting the issue @yuvipanda.
Maybe we could implement something like [lazy importing](https://github.com/Textualize/textual/blob/eb8c07830689e6866c04c9be3a4c87ee298ac5a9/src/textual/widgets/__init__.py#L54) in `xarray-leaflet`?

**Comment by yuvipanda** [comment]
@davidbrochart yep that would seem to be the solution

**Comment by davidbrochart** [comment]
Actually xarray-leaflet doesn't import rioxarray. It depends on it and it uses properties of xarray's DataArray that exist because the array was opened with rioxarray, but that's external to xarray-leaflet.
Also, I don't think I can implement lazy importing anyway, since enabling xarray-leaflet only consists of importing it (it registers a [DataArray accessor](https://github.com/xarray-contrib/xarray_leaflet/blob/88134eefbfdfe3ae5fae2e1e1d0bab1465eb754f/xarray_leaflet/xarray_leaflet.py#L22)).
If rioxarray is the culprit, it might be worth opening an issue there? Although I'm not sure they can do a lot either, it's probably just the time to load GDAL in memory.

**Comment by yuvipanda** [comment]
sorry i misspoke, i meant https://github.com/xarray-contrib/xarray_leaflet/blob/main/xarray_leaflet/xarray_leaflet.py#L16 and rasterio as one of the culprits, not rioxarray. I think IPython is the other big culprit - moving those to be imported just before use might help?

**Comment by davidbrochart** [comment]
Actually there is not need to [import `LeafMap` in `__init__`](https://github.com/xarray-contrib/xarray_leaflet/blob/86da2dfbbe5b0c48b233bb542403df362d5f3af1/xarray_leaflet/__init__.py#L7). One could e.g. `import xarray_leaflet.map` instead of `import xarray_leaflet`. That would be a breaking change though.

**Comment by yuvipanda** [comment]
@davidbrochart right, I'm not sure if a breaking change is desired - I don't know how far along the xarray-leaflet project is.

Another option is to split the serverextension into its own module perhaps? It could ship by default with xarray-leaflet, maybe even as part of the same package, but just be a different module?

**Comment by yuvipanda** [comment]
Thank you so much for your quick work on this, @davidbrochart!
